import tkinter as tk


# 第二个子框-方向符号文本框
class FrameDirectionChar(tk.Frame):
    def __init__(self, master=None):
        tk.Frame.__init__(self, master)
        bg_color_dir_char = "LightSkyBlue"
        self.frame_direction_char_temp = tk.Frame(self, bg=bg_color_dir_char)
        self.label_up_left = tk.Label(self.frame_direction_char_temp, bg=bg_color_dir_char, text="↖")
        self.label_up = tk.Label(self.frame_direction_char_temp, bg=bg_color_dir_char, text="↑")
        self.label_up_right = tk.Label(self.frame_direction_char_temp, bg=bg_color_dir_char, text="↗")
        self.input_up_left = tk.Entry(self.frame_direction_char_temp, width=4, justify=tk.CENTER)
        self.input_up = tk.Entry(self.frame_direction_char_temp, width=4, justify=tk.CENTER)
        self.input_up_right = tk.Entry(self.frame_direction_char_temp, width=4, justify=tk.CENTER)
        self.label_up_left.grid(row=0, column=0)
        self.label_up.grid(row=0, column=1)
        self.label_up_right.grid(row=0, column=2)
        self.input_up_left.grid(row=1, column=0, padx=8)
        self.input_up.grid(row=1, column=1, padx=8)
        self.input_up_right.grid(row=1, column=2, padx=8)
        self.label_left = tk.Label(self.frame_direction_char_temp, bg=bg_color_dir_char, text="←")
        self.label_right = tk.Label(self.frame_direction_char_temp, bg=bg_color_dir_char, text="→")
        self.input_left = tk.Entry(self.frame_direction_char_temp, width=4, justify=tk.CENTER)
        self.input_right = tk.Entry(self.frame_direction_char_temp, width=4, justify=tk.CENTER)
        self.label_left.grid(row=2, column=0)
        self.label_right.grid(row=2, column=2)
        self.input_left.grid(row=3, column=0)
        self.input_right.grid(row=3, column=2)
        self.label_down_left = tk.Label(self.frame_direction_char_temp, bg=bg_color_dir_char, text="↙")
        self.label_down = tk.Label(self.frame_direction_char_temp, bg=bg_color_dir_char, text="↓")
        self.label_down_right = tk.Label(self.frame_direction_char_temp, bg=bg_color_dir_char, text="↘")
        self.input_down_left = tk.Entry(self.frame_direction_char_temp, width=4, justify=tk.CENTER)
        self.input_down = tk.Entry(self.frame_direction_char_temp, width=4, justify=tk.CENTER)
        self.input_down_right = tk.Entry(self.frame_direction_char_temp, width=4, justify=tk.CENTER)
        self.label_down_left.grid(row=4, column=0)
        self.label_down.grid(row=4, column=1)
        self.label_down_right.grid(row=4, column=2)
        self.input_down_left.grid(row=5, column=0)
        self.input_down.grid(row=5, column=1)
        self.input_down_right.grid(row=5, column=2)
        self.frame_direction_char_temp.pack(fill=tk.X, padx=2, pady=2, ipady=2)


'''
        bg_color_dir_char = "LightSkyBlue"
        frame_direction_char = tk.Frame(frame_controls)
        frame_direction_char_temp = tk.Frame(frame_direction_char, bg=bg_color_dir_char)
        label_up_left = tk.Label(frame_direction_char_temp, bg=bg_color_dir_char, text="↖")
        label_up = tk.Label(frame_direction_char_temp, bg=bg_color_dir_char, text="↑")
        label_up_right = tk.Label(frame_direction_char_temp, bg=bg_color_dir_char, text="↗")
        input_up_left = tk.Entry(frame_direction_char_temp, width=4)
        input_up = tk.Entry(frame_direction_char_temp, width=4)
        input_up_right = tk.Entry(frame_direction_char_temp, width=4)
        label_up_left.grid(row=0, column=0)
        label_up.grid(row=0, column=1)
        label_up_right.grid(row=0, column=2)
        input_up_left.grid(row=1, column=0, padx=8)
        input_up.grid(row=1, column=1, padx=8)
        input_up_right.grid(row=1, column=2, padx=8)
        label_left = tk.Label(frame_direction_char_temp, bg=bg_color_dir_char, text="←")
        label_right = tk.Label(frame_direction_char_temp, bg=bg_color_dir_char, text="→")
        input_left = tk.Entry(frame_direction_char_temp, width=4)
        input_right = tk.Entry(frame_direction_char_temp, width=4)
        label_left.grid(row=2, column=0)
        label_right.grid(row=2, column=2)
        input_left.grid(row=3, column=0)
        input_right.grid(row=3, column=2)
        label_down_left = tk.Label(frame_direction_char_temp, bg=bg_color_dir_char, text="↙")
        label_down = tk.Label(frame_direction_char_temp, bg=bg_color_dir_char, text="↓")
        label_down_right = tk.Label(frame_direction_char_temp, bg=bg_color_dir_char, text="↘")
        input_down_left = tk.Entry(frame_direction_char_temp, width=4)
        input_down = tk.Entry(frame_direction_char_temp, width=4)
        input_down_right = tk.Entry(frame_direction_char_temp, width=4)
        label_down_left.grid(row=4, column=0)
        label_down.grid(row=4, column=1)
        label_down_right.grid(row=4, column=2)
        input_down_left.grid(row=5, column=0)
        input_down.grid(row=5, column=1)
        input_down_right.grid(row=5, column=2)
        frame_direction_char_temp.pack(fill=tk.X, padx=2, pady=2, ipady=2)
'''
